name: Build Sillyblue
on:
  schedule:
    - cron:
        "00 06 * * *"
  push:
    paths-ignore:
      - "**.md"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  bluebuild:
    name: Build Sillyblue
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - recipe-sillyblue.yml
    steps:
      - name: Build Sillyblue
        uses: blue-build/github-action@4d8b4df657ec923574611eec6fd7e959416c47f0
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          maximize_build_space: true
